### ISSUE TITLE
Parse issues when the function body is blank

### ISSUE THREAD

**Issue by macthecadillac** [lezer-parser/python#2]
`lezer` version: `0.13.1`
`lezer-python` version: `0.13.2`
`tsc` version: `4.1.3`

# Example:
```python
def foo(a: int, b: int) -> int:

foo(1, 2)
```

## Observed behavior:
The first child of the top-most node is 
```
FunctionDefinition: "def foo(a: int, b: int) -> int:

foo(1, 2)"
```
and once you walk the tree down to the body node, it is
```
Body: ":

foo(1, 2)"
```

## Expected behavior:
```
FunctionDefinition: "def foo(a: int, b: int) -> int:"
```
where the body should be
```
Body: ":"
```

**Comment by marijnh** [comment]
That program isn't valid Python, though, is it?

**Comment by macthecadillac** [comment]
It isn't, but I believe it is the parser's job to check grammar and handle
cases like these.

**Comment by marijnh** [comment]
It's an error-correcting parser. If you set `strict` to true, it'll fail to parse this. But by default, because it is designed for code highlighting, it'll parse anything.

**Comment by macthecadillac** [comment]
I didn't mean it should throw an error and exit; what I meant was `foo(1, 2)` should not be parsed as the function body, whether the parser is error-correcting or not--the parser should either refuse to parse all together or it should parse `foo(1, 2)` as the next statement, not as part of the function definition.

**Comment by R167** [comment]
Followup, this issue still seems present when running in strict mode using `parser.configure({ strict: true }).parse("def test():\npass")`. My guess is it's parsing as a statement based on the below
```python
# This parses and is valid python
def test(): pass

# This also parses (strict), but should not be valid python
def test():
pass
# Running in python here returns
# IndentationError: expected an indented block
```

It appears able to parse a compound statement like so (in strict mode)
```python
def compound():
if True:
  print(1)
```

Because of this, I'm guessing the issue is here:
https://github.com/lezer-parser/python/blob/59a0672d5c966e691b0b87b63c7b0f6232c99121/src/python.grammar#L96

Most likely it picks up the `newline statement`, but doesn't check for any initial indentation for the block (even in strict mode).  ([python](https://docs.python.org/3/reference/grammar.html) denotes this by marking blocks as `block: | NEWLINE INDENT statements DEDENT | simple_stmt`).

not sure though what the difficulty would be enforcing initial indentation on blocks like this

**Comment by marijnh** [comment]
Ah, I see, that's indeed an issue. There's no real guarantees of what comes out when error-correcting, but there should at least be an error marker in there. I've addressed this in patch https://github.com/lezer-parser/python/commit/01a8c44243a844ff17b5d28d1d5448d4e5535414
